### ISSUE TITLE
Basic `make` process

### ISSUE THREAD

**Issue by yunruse** [yunruse/Noether#40]
- [x] `type` for typing with `pyright`
- [x] `test` for testing with `unittest`
- [x] `analyse`, for running analysis code (via `unittest` for now)
- [ ] `build`, which:
  - [x] exports a `catalogue.tar` (or `.zip` with no compression for better performance)
  - [ ] helps prep for pypi upload
- [x] `all`: `type test analyse build`
- [ ] `upload-test` for upload to pypi-test
- [ ] `upload` for upload to pypi
